
//// saving a user 
POST http://localhost:7777/api/users/new-user
Content-Type: application/json

{
    "username": "jay20",
    "email":"jay20@gmail.com",
    "password":"1234"
}


###
/////
GET http://localhost:7777/api/users


###
/////
GET http://localhost:7777/api/users/userInfo




###
POST http://localhost:7777/api/users/login
Content-Type: application/json

{

    "email":"jay20@gmail.com",
    "password":"1234"
}


###
GET http://localhost:7777/api/users/logout
